# Auto-report action script, 3 times a day

name: main report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '30 15,22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install tesseract-ocr unzip -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pillow pytesseract requests
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        EMER_PERSON: ${{ secrets.Emer_person }}
        EMER_RELA: ${{ secrets.Emer_rela }}
        EMER_PHONE: ${{ secrets.Emer_phone }}
        LOCATION : ${{ secrets.LOCATION }}
        DORM_BUILDING: ${{ secrets.DORM_BUILDING }}
        DORM : ${{ secrets.DORM }}
      run: |
        python report.py --data_path data_atschool.json --stuid "$STUID" --password "$PASSWORD" --emer_person "$EMER_PERSON" --relation "$EMER_RELA" --emer_phone "$EMER_PHONE" --location "$LOCATION" --dormbuildingORcityarea "$DORM_BUILDING" --dormORlocation "$DORM" 
